### ISSUE TITLE
Вопросы: JS: tasks/micro-tasks: 1

### ISSUE THREAD

**Issue by kicumkicum** [madekot/teacher-army-labs#1]
Что будет в консоли и почему?

```js
console.log(1);

setTimeout(() => console.log(2), 0);

Promise.resolve().then(() => console.log(3));

console.log(4);
```

**Comment by madekot** [comment]
**если коротко то:** 
1 
4
3
2

**Подробнее**
 js однопоточный язык программирования, что значит, в один момент времени может выполняться одна операция, и для работы с асинхронными операциями был придуман event loop, по сути это бесконечный цикл, который крутится и ожидает на вход различного типа задачи (синхронные, микро таски, макро таски, ) и у этих задач есть разные приоритеты в которой event loop будет закидывать их в стек вызова, где они и будут выполняться. Приоритет у задач такой 
1. синхронные задачи 
2. Все микротаски ( в 99% это промисы, но есть еще функция queueMicrotask() с помощью неё можно создать микро таску, и так же микротаски пораждает mutation oserver.
3. Одна макро таска, если в ней есть синхронный код выполняется он если она порождает микро таски после синхронного кода выполняются они. Дальше следующая макро таска если она есть. (это web Api, setTimeout, setInterval, подписки на события, загрузка картинок)

И так Js, начнет парсить код, сначала выполнит все синхронные операции, в нашем случае 1 и 4

Потом дойдет до макро таски setTimeout передаст эту операцию в webApi после того как таймер закончится webApi передаст эту задачу в очередь задач и когда стек вызова очиститься event loop перекинет её в стек вызова, если не будет микро тасок а у нас они есть поэтому. Дойдет до промиса, он сразу разрезолвелся это микро таска выполнится сразу же после синхронных операций 1 4 3

Ну и вот пришло время для одной макро таски, из setTimeout 1 4 3 2

**Comment by madekot** [comment]
Вот демка из выступление Philip Roberts из 2014 года, очень мне помогло в свое время с этим разобраться [клик](http://latentflip.com/loupe/?code=JC5vbignYnV0dG9uJywgJ2NsaWNrJywgZnVuY3Rpb24gb25DbGljaygpIHsKICAgIHNldFRpbWVvdXQoZnVuY3Rpb24gdGltZXIoKSB7CiAgICAgICAgY29uc29sZS5sb2coJ1lvdSBjbGlja2VkIHRoZSBidXR0b24hJyk7ICAgIAogICAgfSwgMjAwMCk7Cn0pOwoKY29uc29sZS5sb2coIkhpISIpOwoKc2V0VGltZW91dChmdW5jdGlvbiB0aW1lb3V0KCkgewogICAgY29uc29sZS5sb2coIkNsaWNrIHRoZSBidXR0b24hIik7Cn0sIDUwMDApOwoKY29uc29sZS5sb2coIldlbGNvbWUgdG8gbG91cGUuIik7!!!PGJ1dHRvbj5DbGljayBtZSE8L2J1dHRvbj4%3D)

И вот хорошее видео, которое тоже отлично поясняет все тонкости [клик](https://youtu.be/zDlg64fsQow)
Это я себе)) если вдруг забуду как он работает

**Comment by kicumkicum** [comment]
Исчерпывающий ответ, Миша. Круто!

> Вот демка из выступление Philip Roberts из 2014 года

Это прям классика)) Сам ее разбирал когда-то))
