### ISSUE TITLE
Вопросы: JS: variables: 1

### ISSUE THREAD

**Issue by kicumkicum** [madekot/teacher-army-labs#2]
Что будет в консоли и почему?

```js
let foo = {n: 11};
let bar = foo;

bar = {};

console.log(foo);
```

**Comment by madekot** [comment]
**ответ:** {n: 11}

Да, прикольная задачка)) Помню подколола меня в первый раз. Большинство, обычно как видят, что мы переписываем ссылочный тип данных, то думают о мутации. Но тут мы именно затираем ссылку на объект в переменной bar и создаем новую область в памяти, новой ссылкой на новый объект. Это не будет мутацией.

**Comment by kicumkicum** [comment]
Все верно) Молодец!
