### ISSUE TITLE
Вопросы: React: hooks: 1

### ISSUE THREAD

**Issue by kicumkicum** [madekot/teacher-army-labs#6]
Зачем появились хуки в реакте? Какая их задача?

**Comment by madekot** [comment]
**Если коротко:**  Хуки позволяют переиспользовать кусочки логики в функциональных компонентах, подцепляться к методам жизненного цикла компонента, сохранять состояние между рендерами, без хуков функциональный компоненты так не умели. С приходом хуков компоненты стали меньше, проще, понятнее, а меньше кода, меньше багов.

**Развернуто**
В классовых компонентах переиспользовать логику было возможно через компоненты высшего порядка HOC, это было довольно громоздко и запутанно. Плюс приходилось биндить функции, иначе была потеря контекста. This в js ведет себя не так как в большинстве языков, это путало новичков и доставляло боль. Если функциональному компоненту нужно было состояние, его нужно было переписывать в классовый компонент, и обратное, это бесило многих. В защиту классовых компонентов можно сказать, что есть один кейс, который и сейчас возможен только на классовых компонентах, это Error Boundaries или предохранитель.

**Comment by kicumkicum** [comment]
С плюсами хуков разобрались, а как на счет минусов? Какие минусы у них есть в общем или может у какого-нибудь конкретного?

**Comment by madekot** [comment]
К минусам думаю можно отнести 
1) Сложность тестирования, чистые компоненты тестировать очень просто и приятно, а вот когда мы добавляем хуки они теряют свою чистоту.
2) Нужно следить за порядком хуков в компоненте
3) Хук useEffect, нужно правильно определить зависимости, иначе мы получим бесполезные рендеры или не получим их вообще. Следить за побочными эффектами, например удалять функции обработчики событий. Забудем об этом и будет утечка памяти. Нужно учитывать контекст в котором выполняет хук useEffect если он выполняется в разных контекстах.

Есть полезный линт плагин который помогает нам следить за зависимостях в хуке useEffect "eslint-plugin-react-hook"

**Comment by kicumkicum** [comment]
Отлично! Все верно подмечено. От себя еще добавлю, что при работе с ними возникают ситуации, когда кастомный хук использует хук, который использует хук, который использует хук. И отлаживать это просто ад.

Ну и не очевидная работа с замыканием. Эту проблему вроде как решают зависимости (для проверки которых ты назвал плагин) но бывают кейсы, когда все равно все работает не так, как ожидается
